#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$(dirname ${SCRIPT_DIR})

if [ "$(uname)" != "Linux" ]; then
    echo "Please run this under linux"
    exit 1
fi

TOOLCHAIN=x86_64-linux-gnu make -e clean
TOOLCHAIN=x86_64-linux-gnu make -e

rm -f ${ROOT_DIR}/image.hdd
dd if=/dev/zero bs=1M count=0 seek=64 of=${ROOT_DIR}/image.hdd
sgdisk ${ROOT_DIR}/image.hdd -n 1:2048 -t 1:ef00 -m 1
make -C Limine
${ROOT_DIR}/Limine/limine bios-install ${ROOT_DIR}/image.hdd
mformat -i ${ROOT_DIR}/image.hdd@@1M
mmd -i ${ROOT_DIR}/image.hdd@@1M ::/EFI ::/EFI/BOOT ::/boot ::/boot/limine
mcopy -i ${ROOT_DIR}/image.hdd@@1M ${ROOT_DIR}/bin/kernel.elf ::/boot
mcopy -i ${ROOT_DIR}/image.hdd@@1M ${ROOT_DIR}/limine.conf ${ROOT_DIR}/Limine/limine-bios.sys ::/boot/limine
mcopy -i ${ROOT_DIR}/image.hdd@@1M ${ROOT_DIR}/Limine/BOOTX64.EFI ::/EFI/BOOT
mcopy -i ${ROOT_DIR}/image.hdd@@1M ${ROOT_DIR}/Limine/BOOTIA32.EFI ::/EFI/BOOT
