#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$(dirname ${SCRIPT_DIR})

if [ "$(uname)" != "Linux" ]; then
    echo "Please run this under linux"
    exit 1
fi

(qemu-system-x86_64 --bios OVMF.fd -hda ${ROOT_DIR}/image.hdd -vnc 0.0.0.0:59 -cpu Skylake-Client,+x2apic &> /dev/null &)

echo "Started vm with vnc on 0.0.0.0:59"
